image: python:3.8

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_RELEASE_IMAGE_GCP: $GCP_ECR_URI:latest
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375/

stages:
- build
- test
- release
- deploy

test:
  stage: build
  image: python:3.8
  script:
    - "pip install -r requirements.txt"
    - python3 setup.py test
